parameters:
    database_driver: pdo_sqlite
    database_host: localhost
    database_port: null
    database_name: insales_php_app
    database_user: root
    database_password: dbpass
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 5dc159a7790662ededa2f3e4b655e9e4d2d88396
    database_path: /home/slip/www/insales_php_app/app/config/sqlite_base.db

    api_secret: api_secret
    api_key:    api_key
    api_host:   insales-php-app.local
    api_autologin_path: autologin

    application_name: Название приложения
